gateway:
  hostnames:
    - dev.costpilot.online

env:
  appEnv: development
  backendCorsOrigins: http://localhost:3000,https://dev.costpilot.online

auth:
  mode: dev-local
  authority: https://login.microsoftonline.com/common

frontend:
  image:
    digest: ""
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70

identityService:
  image:
    digest: ""
  replicaCount: 2

financeService:
  image:
    digest: ""
  replicaCount: 2

documentsService:
  image:
    digest: ""
  replicaCount: 2

migrationJob:
  image:
    digest: ""
