env:
  appEnv: production
  backendCorsOrigins: https://fin.nexaflow.site,https://myfinagent.online,https://www.myfinagent.online

auth:
  mode: entra
  authority: https://login.microsoftonline.com/common

frontend:
  replicaCount: 2

identityService:
  replicaCount: 2

financeService:
  replicaCount: 2

documentsService:
  replicaCount: 2
