{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVault.secretProviderClassName }}
  namespace: {{ .Values.namespace.name }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secrets.existingSecretName }}
      type: Opaque
      data:
        - objectName: {{ .Values.keyVault.databaseUrlSecretName | quote }}
          key: DATABASE_URL
        - objectName: {{ .Values.keyVault.devAuthSecretSecretName | quote }}
          key: DEV_AUTH_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.azure.managedIdentityClientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.databaseUrlSecretName }}
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.devAuthSecretSecretName }}
          objectType: secret
{{- end }}
